name: C/C++ CI

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push, pull_request]

jobs:
    build:
        name: "Build program"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Build project
              run: |
                  make build

    test:
        name: "Test Program"
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4
            - name: Test project
              run: |
                  make test

    build-deb:
        name: "Building Debian package"
        runs-on: ubuntu-latest
        timeout-minutes: 2
        needs: build
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Build Debian package
              run: |
                  make build-deb
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: merge-sort-v1.0.1.deb
                  path: merge-sort-v1.0.1.deb

    lint-deb:
        name: "Lint Debian Package"
        runs-on: ubuntu-latest
        timeout-minutes: 2
        needs: test
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                  sudo apt update
                  sudo apt install -y lintian

            - name: Lint Debian Package
              run: |
                  make lint-deb
